import React, { useEffect, useMemo, useState } from 'react';
import { inspectPairing, setPairingMode, recordSensoryObservation, whatDidHumanTeach, refinePairing, resetObservations } from './engine.js';
import { registerBlendgineWebMCP } from './webmcp.js';

const reactions = [['😍','delicious','Oh wow'],['🤔','interesting','Interesting'],['✨','balanced','Balanced'],['😵‍💫','overpowering','Too much'],['😂','weirdly good','Weirdly good']];

export default function App(){
 const [mode,setMode]=useState('menu'); const [pairing,setPairing]=useState(()=>inspectPairing({mode:'menu'}));
 const [descriptor,setDescriptor]=useState(pairing.experiment.defaultDescriptor); const [intensity,setIntensity]=useState('medium'); const [phase,setPhase]=useState('overall pairing'); const [humanWords,setHumanWords]=useState(pairing.experiment.defaultWords);
 const [observations,setObservations]=useState([]); const [proposal,setProposal]=useState(null); const [activity,setActivity]=useState([]); const [webmcpReady,setWebmcpReady]=useState(false);
 useEffect(()=>{setWebmcpReady(registerBlendgineWebMCP(event=>setActivity(c=>[event,...c].slice(0,8))));},[]);
 function switchMode(next){const p=setPairingMode(next);setMode(next);setPairing(p);setDescriptor(p.experiment.defaultDescriptor);setHumanWords(p.experiment.defaultWords);setProposal(null);}
 function submitTaste(){const o=recordSensoryObservation({mode,descriptor,intensity,phase,humanWords});setObservations(whatDidHumanTeach().observations);setActivity(c=>[{name:'human_tasting',result:o},...c].slice(0,8));}
 function refine(){const n=refinePairing({mode});setProposal(n);setActivity(c=>[{name:'refinement_proposal',result:n},...c].slice(0,8));}
 function reset(){resetObservations();setObservations([]);setProposal(null);setActivity([]);switchMode('menu');}
 const x=pairing.experiment;
 return <main className="shell">
  <section className="hero"><div className="hero-copy"><div className="eyebrow">✦ BLENDGINE · TEA × FOOD × WEBMCP</div><h1>AI knows the signals.<br/><em>You</em> know the bite.</h1><p className="lede">Pair tea with food using evidence-informed hypotheses, then let an actual human decide what happens in the mouth. Serious pairing menu or absolute chaos—you pick. 😁</p><div className="hero-stickers"><span>🍽️ food</span><b>+</b><span>🍵 tea</span><b>+</b><span>👅 you</span><b>=</b><span>💡 pairing intelligence</span></div></div><div className={`status ${webmcpReady?'ready':''}`}><i/>{webmcpReady?'Agent connected':'WebMCP needs a supported browser'}</div></section>
  <div className="mode-switch"><button className={mode==='menu'?'active':''} onClick={()=>switchMode('menu')}><span>🍽️</span><strong>Pairing Menu</strong><small>restaurant-worthy · zero-proof</small></button><button className={mode==='chaos'?'active chaos':''} onClick={()=>switchMode('chaos')}><span>🤪</span><strong>Chaos Lab</strong><small>weird on purpose · why not?</small></button></div>
  <section className="experiment-banner"><span>{x.modeEmoji} {x.mode.toUpperCase()}</span><strong>{x.tea.name} × {x.food.name}</strong><span className="spark">✦ predict → taste → teach → remix ✦</span></section>
  <section className="grid">
   <article className="card formula-card"><div className="card-head"><div><span className="mini">THE PAIRING</span><h2>{mode==='menu'?'A zero-proof table moment':'This should not work… right?'}</h2></div><span className="pill">{mode==='menu'?'🍷→🍵 alternative pairing':'🎲 chaos approved'}</span></div><div className="pair-stage"><div className="pair-item"><span>{x.food.emoji}</span><strong>{x.food.name}</strong><small>{x.food.detail}</small></div><div className="pair-x">×</div><div className="pair-item"><span>{x.tea.emoji}</span><strong>{x.tea.name}</strong><small>{x.tea.detail}</small></div></div><div className="prep">🫖 {x.tea.preparation}</div><div className="science-box"><span className="mini">💡 WHY BLENDGINE WANTS TO TRY IT</span>{x.hypothesis.basis.map(r=><p key={r}>{r}</p>)}<div className="boundary">⚠️ {x.hypothesis.boundary}</div></div></article>
   <article className="card taste-card"><div className="card-head"><div><span className="mini">👅 YOUR TURN</span><h2>{mode==='menu'?'Taste them together. What changes?':'Be brave. Take the bite + sip. 😂'}</h2></div></div><div className="reaction-row">{reactions.map(([e,v,l])=><button key={v} className={descriptor===v?'selected':''} onClick={()=>setDescriptor(v)}><span>{e}</span>{l}</button>)}</div><label>Say it how you'd actually say it<textarea value={humanWords} onChange={e=>setHumanWords(e.target.value)}/></label><div className="triple"><label>Taste signal<input value={descriptor} onChange={e=>setDescriptor(e.target.value)}/></label><label>How loud?<select value={intensity} onChange={e=>setIntensity(e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label><label>Where?<select value={phase} onChange={e=>setPhase(e.target.value)}><option>first bite + sip</option><option>middle</option><option>finish</option><option>overall pairing</option></select></label></div><button className="primary" onClick={submitTaste}><span>Teach Blendgine</span><b>→</b></button></article>
  </section>
  <section className="grid lower"><article className="card learned-card"><div className="card-head"><div><span className="mini">💬 RECEIPTS</span><h2>What did I teach you?</h2></div><span className="count">{observations.length}</span></div>{observations.length===0?<p className="empty">Nothing yet—and we're not making anything up. Taste first. ☝️</p>:observations.slice().reverse().map(o=><div className="observation" key={o.id}><div className="quote-mark">“</div><p>{o.humanWords}</p><div>{o.tea} × {o.food}</div><small>{o.descriptor} · {o.intensity} · {o.phase} · 🧍 human observation</small></div>)}</article><article className="card next-card"><div className="card-head"><div><span className="mini">🎛️ REMIX</span><h2>What should we try next?</h2></div></div><p>Blendgine can use its pairing hypothesis plus what <em>you actually experienced</em> to propose another tasting—not pretend it tasted anything itself.</p><button className="secondary" onClick={refine}>✨ Remix the pairing</button>{proposal&&<div className="proposal"><strong>{proposal.proposal}</strong><p>{proposal.reason}</p><span>{proposal.status.replaceAll('_',' ')}</span></div>}<button className="ghost" onClick={reset}>↻ Reset lab</button></article></section>
  <section className="activity-wrap"><div className="activity-title"><span className="mini">⚡ WEBMCP LOOP</span><h2>The browser becomes the human + agent tasting table.</h2></div><div className="tool-row">{['🔎 inspect pairing','👅 record tasting','💬 show what I taught','🎛️ refine pairing'].map(t=><span key={t}>{t}</span>)}</div>{activity.length>0&&<div className="activity-log">● Latest move: {activity[0].name.replaceAll('_',' ')}</div>}</section>
  <footer><span>🍽️ food → 🍵 tea hypothesis → 👅 human taste → 💬 attributed evidence → 🎛️ next pairing</span><span>Blendgine · WebMCP Challenge 2026</span></footer>
 </main>;
}
