export const teaProfiles=[
 {id:'fig-leaf',name:'Fig Leaf',detail:'green · herbaceous · softly toasted',ingredients:['fig leaf'],emoji:'🍃',preparation:'slightly toasted · hot infusion',processing:{state:'slightly toasted',source:'assumed_default',confidence:'medium'},signals:['green','herbaceous','toasted','honeyed'],evidenceQuality:3,evidence:{level:'verified',note:'Direct fig-leaf herbal-tea sensory and volatile evidence exists. The demo’s slight toast is a product-context assumption, not a condition tested by the cited paper.',records:[{type:'direct_sensory_and_volatile',ingredient:'Ficus carica leaf herbal tea',plantPart:'leaf',preparationStudied:'air-dried and microwave-dried leaves brewed as herbal tea',citation:'Cincotta et al., Beverages 2025, 11(1), 16',doi:'10.3390/beverages11010016',url:'https://www.mdpi.com/2306-5710/11/1/16',method:'HS-SPME-GC-MS + trained sensory descriptive analysis + consumer testing',findings:['Air-dried tea showed stronger green odor and more bitter/astringent taste and aftertaste.','Microwave drying reduced C6 alcohols/aldehydes associated with green/herbaceous notes and increased fruity/honey-associated volatiles.','Reported volatiles include pentanal, octanal, nonanal, 6-methyl-5-hepten-2-one and beta-cyclocitral.'],supports:['green','herbaceous','honeyed'],doesNotSupport:'toast-specific chemistry'}]}},
 {id:'heal-all',name:'Heal-All',detail:'herbal · green · aromatic',ingredients:['self-heal (Prunella vulgaris)'],emoji:'🌿',preparation:'dried herb · hot infusion',processing:{state:'processed/dried for tea',source:'assumed_default',confidence:'medium'},signals:['green','herbal','aromatic','woody'],evidenceQuality:3,evidence:{level:'verified',note:'Direct Prunella chemistry covers leaf and flower; a separate taste-focused paper connects volatile/aromatic constituents and amino acids to tea/decoction sensory character.',records:[{type:'direct_volatile',ingredient:'Prunella vulgaris',plantPart:'leaf and flower',citation:'Yang & Zhao, Science and Technology of Food Industry 2019, 40(13):180-185,192',doi:'10.13386/j.issn1002-0306.2019.13.029',url:'https://www.spgykj.com/en/article/doi/10.13386/j.issn1002-0306.2019.13.029',method:'GP-MSE/GC-MS',findings:['98 volatile components were identified in leaf and 124 in flower.','Leaf volatile fraction was led by alcohols (26.79%) and aldehydes (15.15%).','Flower chemistry differed substantially from other plant parts.'],supports:['aromatic','plant-part-aware profile']},{type:'direct_taste_context',ingredient:'Prunella vulgaris / Spica Prunellae',plantPart:'flowering spike',citation:'Zhai et al., Zhongguo Zhong Yao Za Zhi 2014;39(3):423-426',pmid:'24946541',url:'https://pubmed.ncbi.nlm.nih.gov/24946541/',method:'GC-MS + amino acid analysis',findings:['Study explicitly discusses effects of aromatic substances on herbal tea/decoction taste.','Beta-ionone was described with cedar/raspberry aroma; nerolidol with weak sweet/orange-blossom/woody character; hexadecanal with floral/waxy character.','Bitter and slightly bitter amino acids had the greatest sensory impact in the analyzed material.'],supports:['aromatic','woody','bitter-context']}]}},
 {id:'rosehip-hibiscus-sumac',name:'Rose Hip · Hibiscus · Sumac',detail:'tangy · fruity · bright · deeply red',ingredients:['rose hip','hibiscus','sumac'],emoji:'🌺',preparation:'dried ingredients · hot infusion',processing:{state:'prepared for tea',source:'assumed_default',confidence:'medium'},signals:['tart','fruity','bright','acidic'],evidenceQuality:1,evidence:{level:'bridged',note:'Ingredient-level evidence exists, but this blend record is still awaiting the same source-by-source tightening as Fig Leaf and Heal-All.',records:[]}},
 {id:'pine-spruce-lemon',name:'Loblolly Pine Needle · Spruce Tip · Lemon',detail:'resinous · evergreen · citrus · bright',ingredients:['loblolly pine needle','spruce tip','lemon'],emoji:'🌲',preparation:'processed edible botanicals · hot infusion',processing:{state:'prepared for tea consumption',source:'assumed_default',confidence:'medium'},signals:['resinous','evergreen','citrus','bright'],evidenceQuality:3,evidence:{level:'verified',note:'Loblolly pine needle chemistry is directly supported. Lemon has separate database coverage. Spruce-tip chemistry is not used as proof in this record until an ingredient-specific source is added.',records:[{type:'direct_volatile',ingredient:'Pinus taeda L. (loblolly pine)',plantPart:'fresh needles',citation:'Pagula & Baeckström, Journal of Essential Oil Research 2006;18(1):32-34',doi:'10.1080/10412905.2006.9699378',url:'https://www.tandfonline.com/doi/abs/10.1080/10412905.2006.9699378',method:'GC + GC/MS',findings:['Loblolly needle oil in the studied sample contained alpha-pinene 62.3%, beta-pinene 7.1%, limonene 2.0%, beta-phellandrene 3.7%, myrcene 1.8%, and alpha-terpineol 2.3%.','Authors note regional variability in chemical composition.'],supports:['resinous','evergreen','citrus-adjacent'],doesNotSupport:'spruce-tip composition or universal percentages across growing regions'}]}},
 {id:'maypop-lemonbalm-chamomile',name:'Maypop Passionflower · Lemon Balm · Chamomile',detail:'floral · lemony · soft · aromatic',ingredients:['maypop passionflower','lemon balm','chamomile'],emoji:'🌼',preparation:'dried botanicals · warm infusion',processing:{state:'prepared/dried for tea',source:'assumed_default',confidence:'medium'},signals:['floral','lemony','soft','aromatic'],evidenceQuality:1,evidence:{level:'bridged',note:'Direct database coverage varies by ingredient; this record remains intentionally lower-confidence until plant-part and preparation-specific sources are attached.',records:[]}}
];

export const foodProfiles=[
 {id:'mushroom-risotto',name:'Mushroom Risotto',detail:'roasted mushrooms · parmesan · thyme',emoji:'🍄',signals:['roasted','earthy','creamy','rich','savory']},
 {id:'dark-chocolate-torte',name:'Dark Chocolate Torte',detail:'cocoa · bittersweet · silky',emoji:'🍫',signals:['bitter','roasted','rich','sweet']},
 {id:'goat-cheese-toast',name:'Goat Cheese Toast',detail:'tangy cheese · toasted bread · olive oil',emoji:'🥖',signals:['tangy','fatty','toasted','savory']},
 {id:'hot-honey-pizza',name:'Hot Honey Pizza',detail:'pepperoni · chile honey · mozzarella',emoji:'🍕',signals:['spicy','sweet','fatty','savory','rich']},
 {id:'birthday-cake',name:'Birthday Cake',detail:'vanilla frosting · butter cake · sprinkles',emoji:'🎂',signals:['sweet','vanilla','creamy','rich']},
 {id:'fried-chicken-waffles',name:'Fried Chicken & Waffles',detail:'crispy chicken · maple · butter',emoji:'🍗',signals:['fried','savory','sweet','fatty','rich']},
 {id:'nacho-cheese-doritos',name:'Nacho Cheese Chips',detail:'cheesy · salty · crunchy · loud',emoji:'🧀',signals:['salty','cheesy','savory','fatty']},
 {id:'sour-gummy-worms',name:'Sour Gummy Worms',detail:'sour sugar · fruit candy · chaos',emoji:'🪱',signals:['sour','fruity','sweet','acidic']},
 {id:'dill-pickle',name:'Dill Pickle',detail:'salty · sour · dill',emoji:'🥒',signals:['salty','sour','herbal','acidic']},
 {id:'honey-bun',name:'Honey Bun',detail:'sticky glaze · cinnamon · soft pastry',emoji:'🍯',signals:['sweet','spiced','rich','baked']}
];

const complement={toasted:['roasted','baked'],honeyed:['sweet','baked'],green:['creamy','fatty'],herbaceous:['savory'],herbal:['savory','cheesy'],aromatic:['spiced'],woody:['roasted'],tart:['rich','sweet'],fruity:['bitter','sour'],bright:['rich','fried'],acidic:['fatty','sweet'],resinous:['sweet','spiced'],evergreen:['sweet','spiced'],citrus:['fried','fatty'],floral:['salty','sour'],lemony:['fried','salty'],soft:['spicy']};
const contrast={green:['rich'],bright:['fatty'],acidic:['rich'],citrus:['rich'],floral:['savory'],soft:['sour'],tart:['fatty'],resinous:['creamy'],evergreen:['rich']};
const chaosFoods=new Set(['hot-honey-pizza','birthday-cake','fried-chicken-waffles','nacho-cheese-doritos','sour-gummy-worms','dill-pickle','honey-bun']);

function scoreTeaFood(tea,food,mode){
 const matchedTeaSignals=new Set();const matchedFoodSignals=new Set();const reasons=[];let relationshipPoints=0;
 for(const signal of tea.signals){for(const f of food.signals){if((complement[signal]||[]).includes(f)){relationshipPoints+=2;matchedTeaSignals.add(signal);matchedFoodSignals.add(f);reasons.push(`${signal} ↔ ${f} complement`);}else if((contrast[signal]||[]).includes(f)){relationshipPoints+=1;matchedTeaSignals.add(signal);matchedFoodSignals.add(f);reasons.push(`${signal} ↔ ${f} contrast`);}}}
 // Breadth matters more than repeatedly hitting generic rich/fatty/sweet signals.
 const breadth=matchedTeaSignals.size*2+matchedFoodSignals.size;
 const genericHits=[...matchedFoodSignals].filter(s=>['rich','fatty','sweet','savory'].includes(s)).length;
 const genericPenalty=Math.max(0,genericHits-2)*2;
 const evidenceBonus=tea.evidenceQuality||0;
 const modeBonus=mode==='chaos'&&chaosFoods.has(food.id)?1:mode==='menu'&&!chaosFoods.has(food.id)?1:0;
 const score=relationshipPoints+breadth+evidenceBonus+modeBonus-genericPenalty;
 return {score,reasons:[...new Set(reasons)],breakdown:{relationshipPoints,breadth,evidenceBonus,modeBonus,genericPenalty,matchedTeaSignals:[...matchedTeaSignals],matchedFoodSignals:[...matchedFoodSignals]}};
}
function matches(item,q){if(!item)return false;const n=String(q).trim().toLowerCase();return [item.name,item.id,...(item.ingredients||[])].some(v=>String(v).toLowerCase()===n||String(v).toLowerCase().includes(n));}
function buildExperiment(tea,food,mode,score){
 const evidence=tea.evidence;const why=score.reasons.slice(0,3);
 return {id:`${mode}-${tea.id}-${food.id}`,mode,modeLabel:mode==='chaos'?'Chaos Lab':'Pairing Menu',modeEmoji:mode==='chaos'?'🤪':'🍽️',food,tea,evidence,hypothesis:{id:`hyp-${tea.id}-${food.id}`,basis:[`Blendgine compared ${tea.name}'s sourced sensory signals (${tea.signals.join(', ')}) with ${food.name}'s food profile.`,why.length?`Strongest candidate signals: ${why.join('; ')}.`:'This is an exploratory candidate with limited signal overlap.',`Score breadth: ${score.breakdown.matchedTeaSignals.length} tea signals × ${score.breakdown.matchedFoodSignals.length} food signals; generic-signal penalty ${score.breakdown.genericPenalty}.`],epistemicStatus:'evidence_informed_hypothesis',boundary:'The ingredient evidence is scientific; the tea-food match is a generated hypothesis, not a scientifically proven preference. Human tasting decides whether it works.'},defaultDescriptor:'interesting',remix:{proposal:`Change one variable—brew strength, temperature, or bite size—and retaste ${tea.name} with ${food.name}.`,reason:'The next proposal uses the human observation to test which sensory variable is driving the experience.'},score:score.score,scoreBreakdown:score.breakdown};
}

export function rankPairings({anchorType='food',anchor='',mode='menu'}={}){
 if(anchorType==='tea'){
  const tea=teaProfiles.find(t=>matches(t,anchor));if(!tea)return [];
  return foodProfiles.map(food=>({tea,food,...scoreTeaFood(tea,food,mode)})).filter(c=>mode!=='chaos'||chaosFoods.has(c.food.id)).sort((a,b)=>b.score-a.score||a.food.name.localeCompare(b.food.name));
 }
 const food=foodProfiles.find(f=>matches(f,anchor));if(!food)return [];
 return teaProfiles.map(tea=>({tea,food,...scoreTeaFood(tea,food,mode)})).sort((a,b)=>b.score-a.score||a.tea.name.localeCompare(b.tea.name));
}
export function findPairing(input={}){const candidates=rankPairings(input);const best=candidates[0];return best?buildExperiment(best.tea,best.food,input.mode==='chaos'?'chaos':'menu',best):null;}

export const defaultPairingId='generated-default';
export const pairingCatalog=[];
export const availableTeas=teaProfiles;
export const availableFoods=foodProfiles;
